import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { PageHeader } from '@/components/ui/PageHeader'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { DataTable, type Column } from '@/components/ui/DataTable'
import { getWorkFile, getWorkFileSection, getWorkpaper, listWorkFiles, runWorkFileAction, runWorkpaperAction, saveWorkpaper, type WorkFile } from '@/api/services/working-papers.service'
import { toApiError } from '@/api/response'
import { toast } from '@/lib/toastStore'

const actionAllowed = (file: WorkFile | undefined, name: string) => Boolean(file?.capabilities[`can_${name}`] ?? file?.capabilities[name])
const status = (value?: string) => <span className="badge rounded-pill text-bg-light border">{value || '-'}</span>
function ErrorState({ error, retry }: { error?: unknown; retry?: () => void }) { return error ? <Card className="border-warning-subtle bg-warning-subtle mb-3"><strong>ไม่สามารถโหลด Working Papers ได้</strong><div className="small mt-1">{toApiError(error).message}</div>{retry && <Button size="sm" variant="secondary" className="mt-2" onClick={retry}>ลองอีกครั้ง</Button>}</Card> : null }
const columns: Column<WorkFile>[] = [
  { key: 'reference', header: 'Reference', cell: item => <Link className="fw-semibold" to={`/working-papers/files/${item.id}`}>{item.reference || item.name}</Link> },
  { key: 'client', header: 'Client', cell: item => item.clientName || '-' }, { key: 'company', header: 'Company', cell: item => item.companyName || '-' },
  { key: 'period', header: 'Period', cell: item => item.period || [item.dateFrom, item.dateTo].filter(Boolean).join(' – ') || '-' },
  { key: 'status', header: 'Status', cell: item => status(item.status) }, { key: 'prepared', header: 'Prepared', cell: item => item.preparedProgress == null ? '-' : `${item.preparedProgress}%` },
  { key: 'reviewed', header: 'Reviewed', cell: item => item.reviewedProgress == null ? '-' : `${item.reviewedProgress}%` }, { key: 'notes', header: 'Review Notes', cell: item => item.openReviewNotes ?? '-' },
]

export function WorkingPapersHomePage() {
  const navigate = useNavigate(); const query = useQuery({ queryKey: ['working-papers', 'files'], queryFn: () => listWorkFiles(), staleTime: 30_000 })
  const files = query.data?.items ?? []; const open = files.filter(file => !['completed', 'locked'].includes((file.status || '').toLowerCase()))
  return <div className="qf-audit-page"><PageHeader title="Working Papers" subtitle="ภาพรวมแฟ้มงานของบริษัทปัจจุบัน ข้อมูลและสิทธิ์มาจาก Odoo" actions={<Button onClick={() => navigate('/working-papers/files')}>ดู Work Files</Button>} /><ErrorState error={query.error} retry={() => void query.refetch()} />
    <div className="row g-3 mb-4">{[['My Open Work Files', open.length], ['Needs Review', files.filter(file => (file.status || '').toLowerCase().includes('review')).length], ['Open Review Notes', files.reduce((n, file) => n + (file.openReviewNotes || 0), 0)]].map(([label, value]) => <div className="col-12 col-md-4" key={String(label)}><Card className="qf-audit-summary"><div className="text-muted small">{label}</div><div className="fs-3 fw-bold mt-1">{value}</div></Card></div>)}</div>
    <DataTable title="My Work Queue" columns={columns} rows={files.slice(0, 8)} rowKey={item => item.id} empty={query.isLoading ? 'กำลังโหลด…' : 'ไม่มี Work Files ที่ได้รับมอบหมาย'} />
  </div>
}

export function WorkFilesPage() { const [search, setSearch] = useState(''); const query = useQuery({ queryKey: ['working-papers', 'files', search], queryFn: () => listWorkFiles({ search }), staleTime: 30_000 }); return <div className="qf-audit-page"><PageHeader title="Work Files" subtitle="ค้นหาและเปิดแฟ้มงานในบริษัทปัจจุบัน" /><Card className="mb-3"><label className="form-label" htmlFor="work-file-search">ค้นหา Client, Company, Work File หรือ Period</label><Input id="work-file-search" value={search} onChange={event => setSearch(event.target.value)} /></Card><ErrorState error={query.error} retry={() => void query.refetch()} /><DataTable columns={columns} rows={query.data?.items || []} rowKey={item => item.id} empty={query.isLoading ? 'กำลังโหลด…' : 'ไม่พบ Work Files'} /></div> }

const sectionLabels: Record<string, string> = { 'trial-balance': 'Trial Balance', leadsheets: 'Leadsheets', workpapers: 'Workpapers', adjustments: 'Adjustments', 'review-notes': 'Review Notes', evidence: 'Evidence / Attachments', activity: 'Activity / Audit Trail' }
export function WorkFilePage() {
  const { workFileId = '' } = useParams(); const navigate = useNavigate(); const qc = useQueryClient(); const [section, setSection] = useState('overview'); const [reason, setReason] = useState('')
  const file = useQuery({ queryKey: ['working-papers', 'file', workFileId], queryFn: () => getWorkFile(workFileId), enabled: Boolean(workFileId) }); const data = useQuery({ queryKey: ['working-papers', 'file', workFileId, section], queryFn: () => getWorkFileSection(workFileId, section as 'trial-balance' | 'leadsheets' | 'workpapers' | 'adjustments' | 'review-notes' | 'evidence' | 'activity'), enabled: Boolean(workFileId && section !== 'overview') })
  const action = useMutation({ mutationFn: ({ name, payload = {} }: { name: 'generate-snapshot' | 'complete' | 'reopen' | 'roll-forward'; payload?: Record<string, unknown> }) => runWorkFileAction(workFileId, name, payload), onSuccess: async (value, variables) => { await qc.invalidateQueries({ queryKey: ['working-papers'] }); toast.success('ดำเนินการสำเร็จ'); if (variables.name === 'roll-forward') navigate(`/working-papers/files/${value.id}`) }, onError: error => toast.error('ดำเนินการไม่สำเร็จ', toApiError(error).message) })
  const workFile = file.data; const run = (name: 'generate-snapshot' | 'complete' | 'reopen' | 'roll-forward') => { if (name === 'reopen' && !reason.trim()) return toast.error('กรุณาระบุเหตุผลในการเปิดแฟ้มงานอีกครั้ง'); action.mutate({ name, payload: name === 'reopen' ? { reason } : {} }) }
  return <div className="qf-audit-page"><PageHeader title={workFile?.name || 'Work File'} subtitle={[workFile?.clientName, workFile?.companyName, workFile?.period].filter(Boolean).join(' · ')} breadcrumb={<Link to="/working-papers/files">Work Files</Link>} actions={<div className="d-flex gap-2 flex-wrap">{actionAllowed(workFile, 'generate_snapshot') && <Button size="sm" variant="secondary" isLoading={action.isPending} onClick={() => run('generate-snapshot')}>Generate Snapshot</Button>}{actionAllowed(workFile, 'complete') && <Button size="sm" isLoading={action.isPending} onClick={() => run('complete')}>Complete</Button>}{actionAllowed(workFile, 'roll_forward') && <Button size="sm" variant="secondary" isLoading={action.isPending} onClick={() => run('roll-forward')}>Roll Forward</Button>}</div>} />
    <ErrorState error={file.error} retry={() => void file.refetch()} />{file.isLoading ? <Card>กำลังโหลด Work File…</Card> : <><Card className="mb-3"><div className="d-flex flex-wrap gap-3 align-items-center">{status(workFile?.status)}<span className="small text-muted">Prepared {workFile?.preparedProgress ?? 0}% · Reviewed {workFile?.reviewedProgress ?? 0}% · TB {workFile?.tbVersion || '—'} · Open notes {workFile?.openReviewNotes ?? 0}</span>{actionAllowed(workFile, 'reopen') && <div className="ms-auto d-flex gap-2"><Input aria-label="เหตุผลในการ Reopen" value={reason} onChange={event => setReason(event.target.value)} placeholder="เหตุผลในการ Reopen" /><Button size="sm" variant="secondary" isLoading={action.isPending} onClick={() => run('reopen')}>Reopen</Button></div>}</div></Card>
      <nav className="nav nav-pills qf-audit-tabs mb-3" aria-label="Work File sections">{['overview', ...Object.keys(sectionLabels)].map(key => <button type="button" key={key} className={`nav-link ${section === key ? 'active' : ''}`} onClick={() => setSection(key)}>{key === 'overview' ? 'Overview' : sectionLabels[key]}</button>)}</nav>
      {section === 'overview' ? <Card><h2 className="h5">Work File overview</h2><p className="text-muted mb-0">สถานะ การคำนวณ และสิทธิ์ดำเนินการเป็นข้อมูลจาก backend โดยตรง</p></Card> : <SectionTable section={section} rows={data.data?.rows || []} loading={data.isLoading} error={data.error} onRetry={() => void data.refetch()} />}</>}</div>
}
function SectionTable({ section, rows, loading, error, onRetry }: { section: string; rows: Record<string, unknown>[]; loading: boolean; error?: unknown; onRetry: () => void }) { const { workFileId = '' } = useParams(); const keys = rows.length ? Object.keys(rows[0]).slice(0, 8) : []; return <><ErrorState error={error} retry={onRetry} /><DataTable title={sectionLabels[section]} columns={keys.map(key => ({ key, header: key.replaceAll('_', ' '), cell: (row: Record<string, unknown>) => section === 'workpapers' && (key === 'reference' || key === 'name') && row.id ? <Link to={`/working-papers/files/${workFileId}/workpapers/${row.id}`}>{String(row[key] ?? row.name ?? row.reference)}</Link> : String(row[key] ?? '-') }))} rows={rows} rowKey={(row, index) => String(row.id ?? index)} empty={loading ? 'กำลังโหลด…' : 'ไม่มีข้อมูล'} /></> }

export function WorkpaperPage() { const { workpaperId = '' } = useParams(); const qc = useQueryClient(); const query = useQuery({ queryKey: ['working-papers', 'workpaper', workpaperId], queryFn: () => getWorkpaper(workpaperId), enabled: Boolean(workpaperId) }); const [draft, setDraft] = useState<Record<string, string> | null>(null); const item = query.data; const values = draft || { objective: item?.objective || '', procedure: item?.procedure || '', result: item?.result || '', conclusion: item?.conclusion || '' }; const save = useMutation({ mutationFn: () => saveWorkpaper(workpaperId, values), onSuccess: () => { setDraft(null); void qc.invalidateQueries({ queryKey: ['working-papers', 'workpaper', workpaperId] }); toast.success('บันทึก Workpaper แล้ว') }, onError: error => toast.error('บันทึกไม่สำเร็จ', toApiError(error).message) }); const workflow = useMutation({ mutationFn: (action: 'prepare' | 'review') => runWorkpaperAction(workpaperId, action), onSuccess: () => { void qc.invalidateQueries({ queryKey: ['working-papers'] }); toast.success('อัปเดตสถานะแล้ว') }, onError: error => toast.error('อัปเดตสถานะไม่สำเร็จ', toApiError(error).message) }); return <div className="qf-audit-page"><PageHeader title={item?.name || 'Workpaper'} subtitle={item?.reference} /><ErrorState error={query.error} retry={() => void query.refetch()} />{item && <Card><div className="row g-3">{(['objective', 'procedure', 'result', 'conclusion'] as const).map(field => <div className="col-12" key={field}><label className="form-label text-capitalize" htmlFor={`workpaper-${field}`}>{field}</label><textarea id={`workpaper-${field}`} className="form-control" rows={field === 'procedure' ? 5 : 3} value={values[field]} disabled={!actionAllowed(item, 'edit')} onChange={event => setDraft({ ...values, [field]: event.target.value })} /></div>)}</div><div className="d-flex flex-wrap gap-2 mt-3">{actionAllowed(item, 'edit') && <Button isLoading={save.isPending} onClick={() => save.mutate()}>Save</Button>}{actionAllowed(item, 'prepare') && <Button variant="secondary" isLoading={workflow.isPending} onClick={() => workflow.mutate('prepare')}>Mark Prepared</Button>}{actionAllowed(item, 'review') && <Button variant="secondary" isLoading={workflow.isPending} onClick={() => workflow.mutate('review')}>Review / Sign Off</Button>}</div></Card>}</div> }
