import { apiClient } from '@/api/client'
import { ApiError, toApiError, unwrapResponse } from '@/api/response'
import { makeRpc } from '@/api/services/rpc'

export interface AuditEngagement { id: string; name: string; clientName?: string; fiscalYear?: string; dateFrom?: string; dateTo?: string; status?: string; progress?: number; leadAuditorName?: string; openReviewNotes?: number; updatedAt?: string }
export interface AuditEngagementListResponse { items: AuditEngagement[]; total?: number }
export interface CreateAuditEngagementPayload { clientId: number; name: string; fiscalYear?: string; dateFrom: string; dateTo: string }
type UnknownRecord = Record<string, unknown>
function stringValue(record: UnknownRecord, ...keys: string[]): string | undefined { for (const key of keys) { const value = record[key]; if (typeof value === 'string' && value.trim()) return value; if (typeof value === 'number') return String(value) } return undefined }
function numberValue(record: UnknownRecord, ...keys: string[]): number | undefined { for (const key of keys) { const value = Number(record[key]); if (Number.isFinite(value)) return value } return undefined }
function relationName(value: unknown): string | undefined { if (typeof value === 'string') return value || undefined; if (Array.isArray(value) && typeof value[1] === 'string') return value[1]; if (value && typeof value === 'object') return stringValue(value as UnknownRecord, 'name', 'display_name', 'displayName'); return undefined }
function mapEngagement(value: unknown): AuditEngagement { const record = (value && typeof value === 'object' ? value : {}) as UnknownRecord; return { id: stringValue(record, 'id', 'engagement_id', 'engagementId') ?? '', name: stringValue(record, 'name', 'display_name', 'displayName', 'engagement_name', 'engagementName') ?? 'ไม่ระบุชื่อ Engagement', clientName: stringValue(record, 'client_name', 'clientName') ?? relationName(record.client_id ?? record.clientId), fiscalYear: stringValue(record, 'fiscal_year', 'fiscalYear'), dateFrom: stringValue(record, 'date_from', 'dateFrom'), dateTo: stringValue(record, 'date_to', 'dateTo'), status: stringValue(record, 'status', 'state'), progress: numberValue(record, 'progress', 'progress_percent', 'progressPercent'), leadAuditorName: stringValue(record, 'lead_auditor_name', 'leadAuditorName') ?? relationName(record.lead_auditor_id ?? record.leadAuditorId), openReviewNotes: numberValue(record, 'open_review_notes', 'openReviewNotes'), updatedAt: stringValue(record, 'updated_at', 'updatedAt', 'write_date') } }
function mapList(value: unknown): AuditEngagementListResponse { const record = (value && typeof value === 'object' ? value : {}) as UnknownRecord; const items = Array.isArray(value) ? value : Array.isArray(record.items) ? record.items : Array.isArray(record.records) ? record.records : []; return { items: items.map(mapEngagement).filter((item) => item.id), total: numberValue(record, 'total', 'count') } }
async function request<T>(path: string, payload: UnknownRecord = {}): Promise<T> { try { return unwrapResponse<T>(await apiClient.post(path, makeRpc(payload))) } catch (error) { const apiError = toApiError(error); if ([404, 405, 501].includes(apiError.status ?? 0)) throw new ApiError('Audit Workspace ยังไม่ได้เปิดใช้งานบน backend ของบริษัทนี้ กรุณาติดต่อผู้ดูแลระบบ', { status: apiError.status }); if ([401, 403].includes(apiError.status ?? 0)) throw new ApiError('คุณไม่มีสิทธิ์เข้าถึงข้อมูล Audit ของบริษัทนี้', { status: apiError.status }); throw apiError } }
export async function listAuditEngagements(params: { search?: string; status?: string } = {}) { return mapList(await request<unknown>('/th/v1/audit/engagements', { ...(params.search ? { search: params.search } : {}), ...(params.status ? { status: params.status } : {}) })) }
export async function getAuditEngagement(id: string) { return mapEngagement(await request<unknown>(`/th/v1/audit/engagements/${encodeURIComponent(id)}`)) }
export async function createAuditEngagement(payload: CreateAuditEngagementPayload) { return mapEngagement(await request<unknown>('/th/v1/audit/engagements', { client_id: payload.clientId, name: payload.name, ...(payload.fiscalYear ? { fiscal_year: payload.fiscalYear } : {}), date_from: payload.dateFrom, date_to: payload.dateTo })) }
